services:
  blue:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm start
    ports:
      - "3000:3000"
  green:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm start
    ports:
      - "3001:3000"
