name: ✨ FiNNi Frontend CI/CD ✨

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    env:
      working-directory: ./finni
    steps:
      - name: ✨ Update permission ✨
        run: sudo chown -R ubuntu:ubuntu /home/ubuntu/actions-runner
      - name: ✨ Checkout code ✨
        uses: actions/checkout@v4
      - name: ✨ Generate Environment Variables File ✨
        run: |
          touch .env
          echo "REACT_APP_BACKEND_IP=$REACT_APP_BACKEND_IP" >> .env
          echo "REACT_APP_CLIENT_ID=$REACT_APP_CLIENT_ID" >> .env
          echo "REACT_APP_CLIENT_IP=$REACT_APP_CLIENT_IP" >> .env
          echo "REACT_APP_REST_API_KEY=$REACT_APP_REST_API_KEY" >> .env
        env:
          REACT_APP_BACKEND_IP: ${{ secrets.REACT_APP_BACKEND_IP }}
          REACT_APP_CLIENT_ID: ${{ secrets.REACT_APP_CLIENT_ID }}
          REACT_APP_CLIENT_IP: ${{ secrets.REACT_APP_CLIENT_IP }}
          REACT_APP_REST_API_KEY: ${{ secrets.REACT_APP_REST_API_KEY }}
      - name: ✨ Deploy ✨
        run: |
          export NODE_OPTIONS="--max-old-space-size=2048"
          chmod +x /home/ubuntu/deploy_frontend.sh
          sh /home/ubuntu/deploy_frontend.sh
